public class Pok_arr {
	public static Pokemon[][] pok_arr = 
		{  
		   {  new Pokemon("캐터피",1,Skill_arr.skills[1]),
			  new Pokemon("캐터피",2,Skill_arr.skills[1]),		
			  new Pokemon("캐터피",3,Skill_arr.skills[1]),		
			  new Pokemon("꼬렛",4,Skill_arr.skills[1]),		
			  new Pokemon("꼬렛",5,Skill_arr.skills[1]),		
			  new Pokemon("꼬렛",6,Skill_arr.skills[1]),		
			  new Pokemon("구구",7,Skill_arr.skills[10]),		
			  new Pokemon("구구",8,Skill_arr.skills[10]),		
			  new Pokemon("구구",9,Skill_arr.skills[10])	,
			  new Pokemon("나옹",10,Skill_arr.skills[7])
			},
			{ new Pokemon("꼬마돌",11,Skill_arr.skills[11]),
			  new Pokemon("꼬마돌",12,Skill_arr.skills[11]),		
			  new Pokemon("꼬마돌",13,Skill_arr.skills[11]),		
			  new Pokemon("꼬마돌",14,Skill_arr.skills[11]),		
			  new Pokemon("알통몬",15,Skill_arr.skills[9]),		
			  new Pokemon("알통몬",16,Skill_arr.skills[9]),		
			  new Pokemon("알통몬",17,Skill_arr.skills[9]),		
			  new Pokemon("알통몬",18,Skill_arr.skills[9]),		
			  new Pokemon("알통몬",19,Skill_arr.skills[9]),		
			  new Pokemon("롱스톤",20,Skill_arr.skills[25]),		
			},
			{ new Pokemon("고라파덕",21,Skill_arr.skills[12]),
			  new Pokemon("고라파덕",22,Skill_arr.skills[12]),		
			  new Pokemon("고라파덕",23,Skill_arr.skills[12]),		
			  new Pokemon("고라파덕",24,Skill_arr.skills[12]),		
			  new Pokemon("왕눈해",25,Skill_arr.skills[13]),		
			  new Pokemon("왕눈해",26,Skill_arr.skills[13]),		
			  new Pokemon("왕눈해",27,Skill_arr.skills[13]),		
			  new Pokemon("왕눈해",28,Skill_arr.skills[13]),		
			  new Pokemon("왕눈해",29,Skill_arr.skills[13]),		
			  new Pokemon("아쿠스타",30,Skill_arr.skills[26]),		
			},	
			{ new Pokemon("붐볼",31,Skill_arr.skills[14]),
			  new Pokemon("붐볼",32,Skill_arr.skills[14]),		
			  new Pokemon("붐볼",33,Skill_arr.skills[14]),		
			  new Pokemon("붐볼",34,Skill_arr.skills[14]),		
			  new Pokemon("레어코일",35,Skill_arr.skills[15]),		
			  new Pokemon("레어코일",36,Skill_arr.skills[15]),		
			  new Pokemon("레어코일",37,Skill_arr.skills[15]),		
			  new Pokemon("레어코일",38,Skill_arr.skills[15]),		
			  new Pokemon("레어코일",39,Skill_arr.skills[15]),		
			  new Pokemon("라이츄",40,Skill_arr.skills[27]),		
			},
			{ new Pokemon("파라섹트",41,Skill_arr.skills[7]),
	    	  new Pokemon("파라섹트",42,Skill_arr.skills[7]),		
	    	  new Pokemon("파라섹트",43,Skill_arr.skills[7]),		
	    	  new Pokemon("우츠보트",44,Skill_arr.skills[23]),		
	    	  new Pokemon("우츠보트",45,Skill_arr.skills[23]),		
	    	  new Pokemon("우츠보트",46,Skill_arr.skills[23]),		
	    	  new Pokemon("니드킹",47,Skill_arr.skills[24]),		
	    	  new Pokemon("니드킹",48,Skill_arr.skills[24]),		
	    	  new Pokemon("니드킹",49,Skill_arr.skills[24]),		
	    	  new Pokemon("라플레시아",49,Skill_arr.skills[28]),		
			},
			
			{ new Pokemon("버터풀",51,Skill_arr.skills[16]),
			  new Pokemon("버터풀",52,Skill_arr.skills[16]),		
			  new Pokemon("버터풀",53,Skill_arr.skills[16]),		
			  new Pokemon("도나리",54,Skill_arr.skills[17]),		
			  new Pokemon("도나리",55,Skill_arr.skills[17]),		
			  new Pokemon("도나리",56,Skill_arr.skills[17]),		
			  new Pokemon("독침붕",57,Skill_arr.skills[18]),		
			  new Pokemon("독침붕",58,Skill_arr.skills[18]),		
			  new Pokemon("독침붕",59,Skill_arr.skills[18]),		
			  new Pokemon("도나리",59,Skill_arr.skills[17]),		
			},	
			{ new Pokemon("야도란",61,Skill_arr.skills[19]),
			  new Pokemon("야도란",62,Skill_arr.skills[19]),		
			  new Pokemon("야도란",63,Skill_arr.skills[19]),		
			  new Pokemon("윤겔라",64,Skill_arr.skills[20]),		
			  new Pokemon("윤겔라",65,Skill_arr.skills[20]),		
			  new Pokemon("윤겔라",66,Skill_arr.skills[20]),		
			  new Pokemon("슬리퍼",67,Skill_arr.skills[21]),		
			  new Pokemon("슬리퍼",68,Skill_arr.skills[21]),		
			  new Pokemon("슬리퍼",69,Skill_arr.skills[21]),		
			  new Pokemon("후딘",69,Skill_arr.skills[29]),		
			},	
			{ new Pokemon("가디",71,Skill_arr.skills[7]),
			  new Pokemon("가디",72,Skill_arr.skills[7]),		
			  new Pokemon("가디",73,Skill_arr.skills[7]),		
			  new Pokemon("리자드",74,Skill_arr.skills[8]),		
			  new Pokemon("리자드",75,Skill_arr.skills[8]),		
			  new Pokemon("리자드",76,Skill_arr.skills[8]),		
			  new Pokemon("날쌩마",77,Skill_arr.skills[22]),		
			  new Pokemon("날쌩마",78,Skill_arr.skills[22]),		
			  new Pokemon("날쌩마",79,Skill_arr.skills[22]),		
			  new Pokemon("윈디",79,Skill_arr.skills[30]),		
    		},	
				
		};
	
}